name: Build and Release

on: [push]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'
      - name: Install dependencies
        run: yarn install
      - name: Build and Package App
        run: yarn make
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: out/make/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.STAR_CRAWLFT_TOKEN }}
